# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  my_job_1:
    docker:
      - image: hello-world
    working_directory: ~/myproj
    steps:
      - run:
          name: demo stpe 1
          command: pwd

  my_job_2:
    docker:
      - image: hello-world
    working_directory: ~/myproj
    steps:
      - run:
          name: demo stpe 2
          command: pwd

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  myworkflow:
    # Run the welcome/run job in its own container
    jobs:
      - my_job_1
      - my_job_2
