# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/myproj
    steps:
      - run:
          name: demo stpe 1
          command: df -H
      - run: |
          pwd
          ls -ltra
      - run: mkdir -p workspace
      - run: echo "hello world !" > workspce/test.log
      - persist_to_workspace:
          root: workspace
          paths: test.log

  api_test:
    docker:
      - image: circleci/node:10
    # working_directory: ~/myproj
    steps:
      - attach_workspace:
          at: ~/myproj/workspace
      - run:
          name: demo stpe 1
          command: df -H
      - run: |
          if [[ `cat ~/myproj/workspace/test.log` == "hello world !" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

  ui_test:
    docker:
      - image: circleci/node:10
    working_directory: ~/myproj
    steps:
      - run:
          name: demo stpe 2
          command: echo $user1
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/myproj
    steps:
      - run:
          name: demo stpe 2
          command: echo $user1

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  commit_workflow:
    # Run the welcome/run job in its own container
    jobs:
      - build
      # - hold:
      #    type: approval
      #    requires:
      #      - api_test
      #      - ui_test
      - api_test:
          requires:
            - build
      - ui_test:
          requires:
            - build
      - deploy:
          requires:
            # - hold
            - ui_test
            - api_test
          context: prod

  every-mins:
    triggers:
      - schedule:
          cron: "25 * * * *"
          filters:
            branches:
              only:
                # - circleci-project-setup
                - disabled
    jobs:
      - build
